[env]
TERM = "xterm-256color"

[window]
padding.x = 0
padding.y = 0
dynamic_padding = true
opacity = 0.92

[font]
size = 11

normal.family = "JetBrainsMono Nerd Font"
normal.style = "Regular"

bold.family = "JetBrainsMono Nerd Font"
bold.style = "Bold"

italic.family = "JetBrainsMono Nerd Font"
italic.style = "Italic"

bold_italic.family = "JetBrainsMono Nerd Font"
bold_italic.style = "Bold Italic"

[[keyboard.bindings]]
action = "Paste"
key = "V"
mods = "Control"

[[keyboard.bindings]]
action = "Copy"
key = "C"
mods = "Control"
